name: "CodeQL Security Inspection"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "39 19 * * 4"

jobs:
  code-security:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ["typescript", "javascript"]

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
